In [1]:
# Dependencies
import pandas as pd

In [2]:
# Read CSV
csv = pd.read_csv('Population.csv')
csv

,Series Name,Series Code,Country Name,Country Code,1990 [YR1990],1991 [YR1991],1992 [YR1992],1993 [YR1993],1994 [YR1994],1995 [YR1995],...,2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020]
0,"Population, total",SP.POP.TOTL,Australia,AUS,17065100.0,17284000.0,17495000.0,17667000.0,17855000.0,18072000.0,...,22340024.0,22733465.0,23128129.0,23475686.0,23815995.0,24190907.0,24601860.0,24982688.0,25364307.0,..
1,"Population, total",SP.POP.TOTL,Canada,CAN,27691138.0,28037420.0,28371264.0,28684764.0,29000663.0,29302311.0,...,34339328.0,34714222.0,35082954.0,35437435.0,35702908.0,36109487.0,36543321.0,37057765.0,37589262.0,..
2,"Population, total",SP.POP.TOTL,Japan,JPN,123537000.0,123921000.0,124229000.0,124536000.0,124961000.0,125439000.0,...,127833000.0,127629000.0,127445000.0,127276000.0,127141000.0,126994511.0,126785797.0,126529100.0,126264931.0,..
3,"Population, total",SP.POP.TOTL,Russian Federation,RUS,147969407.0,148394216.0,148538197.0,148458777.0,148407912.0,148375787.0,...,142960908.0,143201721.0,143506995.0,143819666.0,144096870.0,144342396.0,144496740.0,144477860.0,144373535.0,..
4,"Population, total",SP.POP.TOTL,Spain,ESP,38867322.0,38966376.0,39157685.0,39361262.0,39549108.0,39724050.0,...,46742697.0,46773055.0,46620045.0,46480882.0,46444832.0,46484062.0,46593236.0,46797754.0,47076781.0,..
5,"Population, total",SP.POP.TOTL,Turkey,TUR,53921760.0,54840590.0,55748948.0,56653804.0,57564204.0,58486456.0,...,73443863.0,74653016.0,75928564.0,77231907.0,78529409.0,79821724.0,81101892.0,82319724.0,83429615.0,..
6,"Population, total",SP.POP.TOTL,United States,USA,249623000.0,252981000.0,256514000.0,259919000.0,263126000.0,266278000.0,...,311556874.0,313830990.0,315993715.0,318301008.0,320635163.0,322941311.0,324985539.0,326687501.0,328239523.0,..
7,"Population, total",SP.POP.TOTL,United Kingdom,GBR,57247586.0,57424897.0,57580402.0,57718614.0,57865745.0,58019030.0,...,63258810.0,63700215.0,64128273.0,64602298.0,65116219.0,65611593.0,66058859.0,66460344.0,66834405.0,..
8,"Population, total",SP.POP.TOTL,Switzerland,CHE,6715519.0,6799978.0,6875364.0,6938265.0,6993795.0,7040687.0,...,7912398.0,7996861.0,8089346.0,8188649.0,8282396.0,8373338.0,8451840.0,8514329.0,8574832.0,..
9,"Population, total",SP.POP.TOTL,New Zealand,NZL,3329800.0,3495100.0,3531700.0,3572200.0,3620000.0,3673400.0,...,4384000.0,4408100.0,4442100.0,4509700.0,4595700.0,4693200.0,4793900.0,4841000.0,4917000.0,..
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Last Updated: 12/16/2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Drop Columns
cols = csv.drop(columns=['Series Name', 'Series Code', 'Country Code'])
cols

,Country Name,1990 [YR1990],1991 [YR1991],1992 [YR1992],1993 [YR1993],1994 [YR1994],1995 [YR1995],1996 [YR1996],1997 [YR1997],1998 [YR1998],...,2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020]
0,Australia,17065100.0,17284000.0,17495000.0,17667000.0,17855000.0,18072000.0,18311000.0,18517000.0,18711000.0,...,22340024.0,22733465.0,23128129.0,23475686.0,23815995.0,24190907.0,24601860.0,24982688.0,25364307.0,..
1,Canada,27691138.0,28037420.0,28371264.0,28684764.0,29000663.0,29302311.0,29610218.0,29905948.0,30155173.0,...,34339328.0,34714222.0,35082954.0,35437435.0,35702908.0,36109487.0,36543321.0,37057765.0,37589262.0,..
2,Japan,123537000.0,123921000.0,124229000.0,124536000.0,124961000.0,125439000.0,125757000.0,126057000.0,126400000.0,...,127833000.0,127629000.0,127445000.0,127276000.0,127141000.0,126994511.0,126785797.0,126529100.0,126264931.0,..
3,Russian Federation,147969407.0,148394216.0,148538197.0,148458777.0,148407912.0,148375787.0,148160129.0,147915361.0,147670784.0,...,142960908.0,143201721.0,143506995.0,143819666.0,144096870.0,144342396.0,144496740.0,144477860.0,144373535.0,..
4,Spain,38867322.0,38966376.0,39157685.0,39361262.0,39549108.0,39724050.0,39889852.0,40057389.0,40223509.0,...,46742697.0,46773055.0,46620045.0,46480882.0,46444832.0,46484062.0,46593236.0,46797754.0,47076781.0,..
5,Turkey,53921760.0,54840590.0,55748948.0,56653804.0,57564204.0,58486456.0,59423282.0,60372568.0,61329676.0,...,73443863.0,74653016.0,75928564.0,77231907.0,78529409.0,79821724.0,81101892.0,82319724.0,83429615.0,..
6,United States,249623000.0,252981000.0,256514000.0,259919000.0,263126000.0,266278000.0,269394000.0,272657000.0,275854000.0,...,311556874.0,313830990.0,315993715.0,318301008.0,320635163.0,322941311.0,324985539.0,326687501.0,328239523.0,..
7,United Kingdom,57247586.0,57424897.0,57580402.0,57718614.0,57865745.0,58019030.0,58166950.0,58316954.0,58487141.0,...,63258810.0,63700215.0,64128273.0,64602298.0,65116219.0,65611593.0,66058859.0,66460344.0,66834405.0,..
8,Switzerland,6715519.0,6799978.0,6875364.0,6938265.0,6993795.0,7040687.0,7071850.0,7088906.0,7110001.0,...,7912398.0,7996861.0,8089346.0,8188649.0,8282396.0,8373338.0,8451840.0,8514329.0,8574832.0,..
9,New Zealand,3329800.0,3495100.0,3531700.0,3572200.0,3620000.0,3673400.0,3732000.0,3781300.0,3815000.0,...,4384000.0,4408100.0,4442100.0,4509700.0,4595700.0,4693200.0,4793900.0,4841000.0,4917000.0,..
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
# Drop Rows
rows = cols.drop([10, 11, 12, 13, 14])
rows

,Country Name,1990 [YR1990],1991 [YR1991],1992 [YR1992],1993 [YR1993],1994 [YR1994],1995 [YR1995],1996 [YR1996],1997 [YR1997],1998 [YR1998],...,2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020]
0,Australia,17065100.0,17284000.0,17495000.0,17667000.0,17855000.0,18072000.0,18311000.0,18517000.0,18711000.0,...,22340024.0,22733465.0,23128129.0,23475686.0,23815995.0,24190907.0,24601860.0,24982688.0,25364307.0,..
1,Canada,27691138.0,28037420.0,28371264.0,28684764.0,29000663.0,29302311.0,29610218.0,29905948.0,30155173.0,...,34339328.0,34714222.0,35082954.0,35437435.0,35702908.0,36109487.0,36543321.0,37057765.0,37589262.0,..
2,Japan,123537000.0,123921000.0,124229000.0,124536000.0,124961000.0,125439000.0,125757000.0,126057000.0,126400000.0,...,127833000.0,127629000.0,127445000.0,127276000.0,127141000.0,126994511.0,126785797.0,126529100.0,126264931.0,..
3,Russian Federation,147969407.0,148394216.0,148538197.0,148458777.0,148407912.0,148375787.0,148160129.0,147915361.0,147670784.0,...,142960908.0,143201721.0,143506995.0,143819666.0,144096870.0,144342396.0,144496740.0,144477860.0,144373535.0,..
4,Spain,38867322.0,38966376.0,39157685.0,39361262.0,39549108.0,39724050.0,39889852.0,40057389.0,40223509.0,...,46742697.0,46773055.0,46620045.0,46480882.0,46444832.0,46484062.0,46593236.0,46797754.0,47076781.0,..
5,Turkey,53921760.0,54840590.0,55748948.0,56653804.0,57564204.0,58486456.0,59423282.0,60372568.0,61329676.0,...,73443863.0,74653016.0,75928564.0,77231907.0,78529409.0,79821724.0,81101892.0,82319724.0,83429615.0,..
6,United States,249623000.0,252981000.0,256514000.0,259919000.0,263126000.0,266278000.0,269394000.0,272657000.0,275854000.0,...,311556874.0,313830990.0,315993715.0,318301008.0,320635163.0,322941311.0,324985539.0,326687501.0,328239523.0,..
7,United Kingdom,57247586.0,57424897.0,57580402.0,57718614.0,57865745.0,58019030.0,58166950.0,58316954.0,58487141.0,...,63258810.0,63700215.0,64128273.0,64602298.0,65116219.0,65611593.0,66058859.0,66460344.0,66834405.0,..
8,Switzerland,6715519.0,6799978.0,6875364.0,6938265.0,6993795.0,7040687.0,7071850.0,7088906.0,7110001.0,...,7912398.0,7996861.0,8089346.0,8188649.0,8282396.0,8373338.0,8451840.0,8514329.0,8574832.0,..
9,New Zealand,3329800.0,3495100.0,3531700.0,3572200.0,3620000.0,3673400.0,3732000.0,3781300.0,3815000.0,...,4384000.0,4408100.0,4442100.0,4509700.0,4595700.0,4693200.0,4793900.0,4841000.0,4917000.0,..

In [5]:
# Rename Columns
cols_name = ['Country', 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011,
             2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020]

In [6]:
# Make Duplicate DF, Replace Column Names
pop = rows.copy()
pop.columns = cols_name
pop

,Country,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
0,Australia,17065100.0,17284000.0,17495000.0,17667000.0,17855000.0,18072000.0,18311000.0,18517000.0,18711000.0,...,22340024.0,22733465.0,23128129.0,23475686.0,23815995.0,24190907.0,24601860.0,24982688.0,25364307.0,..
1,Canada,27691138.0,28037420.0,28371264.0,28684764.0,29000663.0,29302311.0,29610218.0,29905948.0,30155173.0,...,34339328.0,34714222.0,35082954.0,35437435.0,35702908.0,36109487.0,36543321.0,37057765.0,37589262.0,..
2,Japan,123537000.0,123921000.0,124229000.0,124536000.0,124961000.0,125439000.0,125757000.0,126057000.0,126400000.0,...,127833000.0,127629000.0,127445000.0,127276000.0,127141000.0,126994511.0,126785797.0,126529100.0,126264931.0,..
3,Russian Federation,147969407.0,148394216.0,148538197.0,148458777.0,148407912.0,148375787.0,148160129.0,147915361.0,147670784.0,...,142960908.0,143201721.0,143506995.0,143819666.0,144096870.0,144342396.0,144496740.0,144477860.0,144373535.0,..
4,Spain,38867322.0,38966376.0,39157685.0,39361262.0,39549108.0,39724050.0,39889852.0,40057389.0,40223509.0,...,46742697.0,46773055.0,46620045.0,46480882.0,46444832.0,46484062.0,46593236.0,46797754.0,47076781.0,..
5,Turkey,53921760.0,54840590.0,55748948.0,56653804.0,57564204.0,58486456.0,59423282.0,60372568.0,61329676.0,...,73443863.0,74653016.0,75928564.0,77231907.0,78529409.0,79821724.0,81101892.0,82319724.0,83429615.0,..
6,United States,249623000.0,252981000.0,256514000.0,259919000.0,263126000.0,266278000.0,269394000.0,272657000.0,275854000.0,...,311556874.0,313830990.0,315993715.0,318301008.0,320635163.0,322941311.0,324985539.0,326687501.0,328239523.0,..
7,United Kingdom,57247586.0,57424897.0,57580402.0,57718614.0,57865745.0,58019030.0,58166950.0,58316954.0,58487141.0,...,63258810.0,63700215.0,64128273.0,64602298.0,65116219.0,65611593.0,66058859.0,66460344.0,66834405.0,..
8,Switzerland,6715519.0,6799978.0,6875364.0,6938265.0,6993795.0,7040687.0,7071850.0,7088906.0,7110001.0,...,7912398.0,7996861.0,8089346.0,8188649.0,8282396.0,8373338.0,8451840.0,8514329.0,8574832.0,..
9,New Zealand,3329800.0,3495100.0,3531700.0,3572200.0,3620000.0,3673400.0,3732000.0,3781300.0,3815000.0,...,4384000.0,4408100.0,4442100.0,4509700.0,4595700.0,4693200.0,4793900.0,4841000.0,4917000.0,..

In [7]:
# Save DF as CSV
pop.to_csv('Population - Cleaned.csv')